# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: "3.4"

services:
  vuttr:
    container_name: vuttr
    user: root
    image: vuttr
    build:
      context: .
      dockerfile: VUTTR/src/Dockerfile
    ports:
      - 3000:3000
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Data Source=sqlserver;Initial Catalog=Vuttr;User ID=sa;Password=Nova@Senha123Legal
    depends_on:
      - sqlserver

  sqlserver:
    container_name: sqlserver
    user: root
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "Nova@Senha123Legal"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    expose:
      - 1433
    restart: always
    volumes:
      - /VUTTR/src/Infra/Volumes/data:/var/opt/mssql/data
      - /VUTTR/src/Infra/Volumes/log:/var/opt/mssql/log
      - /VUTTR/src/Infra/Volumes/secrets:/var/opt/mssql/secrets